### ISSUE TITLE
Move location of swimR templates

### ISSUE THREAD

**Issue by landisrm** [tlumip/tlumip#111]
Currently SWIM renders the swimR templates that are built into the R package.  This makes it difficult to modify them because they would need to be updated in the dependencies64.zip file.  

To do:
  - copy swimR markdown templates to a new location like root/scenario/model/code/swimr
  - point to the new location in root/scenario/model/viz/swimr_render_rmd.R.  (this file should also be moved to root/scenario/model/code/swimr).
  - keep templates in the R package for testing purposes, documentation, and for when users run functions in the swimr package in RStudio outside the context of a SWIM run. 
   - Update documentation to point to both locations (the templates in the R package for testing and the templates in root/scenario/model/code/) so there is no confusion about where they exist and what they are for.

**Comment by bettinardi** [comment]
Capturing a quick reminder on where the templates are currently kept: https://github.com/tlumip/tlumip_dependencies/blob/master/R-3.3.2/library/swimr/rmarkdown/templates/single_scenario/skeleton/skeleton.Rmd

**Comment by bettinardi** [comment]
Capturing some notes when we get back to this.

There's an issue in the "compare" markdown template when we push out to 2050 and ignore years 2009-2019, something in lines - 134-141 of skeleton.Rmd
D:\swim2\model\lib\R-3.3.2\library\swimr\rmarkdown\templates\compare_scenario\skeleton

For the population template - 
D:\swim2\model\lib\R-3.3.2\library\swimr\rmarkdown\templates\population\skeleton

The skeleton markdown file assumes regions 1:9 in 4 or 5 locations.  We have since updated to 6 regions.  This should be a user specified input at the top of the template.   All three templates should be scenario specific and stored and customized for the scenario - which is the point of this issue.

**Comment by bettinardi** [comment]
Summarizing for WOC 7 
See the steps laid out in the first and second comments.  
After that is addressed (the location of the template), note that it would be ideal to provide some hours to look back at some of these templates and address some known issues - comment 3 provides some of these.
