### ISSUE TITLE
update average viz db script

### ISSUE THREAD

**Issue by bstabler** [tlumip/tlumip#73]
Update the average viz dbs script so the output looks like a regular viz db, but with data fields replaced with averages where specified.  The script will copy the first viz db and then replace specified fields with the average across multiple dbs. 

Also add the average viz db documentation to the wiki.

**Comment by bstabler** [comment]
Update this page as well - https://github.com/pbsag/tlumip/wiki/Helper-Scripts

**Comment by nsdhakar** [comment]
Following key updates are made to the script:
1. The master table was not supposed to have NULL in "key_fld" in the second part. Now, updated the script to accept NULL, such fields are considered as KEYS so that all fields are present in the output database. Also, if all fields of a table are set to NULL, the table is still written out in the output database.
2. If a field values contain "None" then the field column was read as character/factor. If such field is assigned as FLDS to average then the script threw an error due to non-numeric values. Now, before averaging, the fields that need to be averaged are converted to numeric to avoid this error.
3. If a field name contains dot (".") then sql query throws an error (ex. TOLL_PRTSYS.A., TOLL_PRTSYS.D.). Now, such fields are ignored and are not output in the averaged database. A warning is printed for user to correct the name in the database.

**Comment by bstabler** [comment]
@bettinardi to update the template [DataBaseDescription.csv](https://github.com/pbsag/tlumip/blob/master/root/scenario/model/helper_scripts/DataBaseDescription.csv)

**Comment by bettinardi** [comment]
Currently the process successfully builds an averaged database, however to speed up completing this script, it was left mainly as it was originally developed.  What that means is that it does not copy a database and average certain fields.  It creates an empty database and fills it with all the tables it is supposed to have.

This is currently leading to some issues.  The one known one is that the table / field headers have all been turned to uppercase.  This needs to be updated so that the case remains consistent.  

I am anticipating other currently unknown issues to arise as well, as testing continues.  This will likely be a work in progress for a little while.

**Comment by bettinardi** [comment]
This is on Alex to close.
I would have already closed it, but I'm realizing some new ODOT security change is stopping my ability to push and pull from git - so once I get that working again, I will update the repo and close this ticket.

**Comment by bettinardi** [comment]
Closing now
