### ISSUE TITLE
What is the trusted source of Value flow from SWIM

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#78]
For freight work, we (ODOT) often get asked questions about how truck value and tonnage is moving around the network.

The question is, should we trust the AA buy-sell matrix more than the FAF data from CT, or visa-versa.

Along these lines, we also need to explore what the difference is between these two and if we are okay with any difference we find - lastly, if when looking at CT output, we should look at just "FAF" or also "CT" (local) trip flows...

**Comment by jeabraham** [comment]
Hmm, if they are asking for economic analysis I'd want to use AA's matrices.

--
John Abraham
jea@hbaspecto.com
403-232-1060

**Comment by rickdonnelly** [comment]
The AA and CT modules have evolved with varying degrees of integration and consistency over the years. AA is similar in many respects to classical multi-region input-output models in formulation and output data, although unique in microsimulation approach that enables very high level of spatial and temporal resolutions. From freight modeling standpoint AA produces several useful outputs, to include production-consumption (PC) matrices by commodity and make and use coefficients. These represent state of the art inputs to commodity flow modeling even today, and have been used in one form or another throughout evolution of the CT model.

The original CT prototype pre-dated AA and focused mostly on intercity truck flows. It munged  aggregate data from the 1997 and 2003 Commodity Flow Survey (CFS) and microdata from the 2002 Vehicle Inventory and Use Survey (VIUS). When AA came online CT was overhauled to directly use the PC matrices to depict OD flows at the beta zone level and the make and use coefficients to allocate flows to specific alpha zones within the betas. We derived truckload equivalents (tons to trucks) derived from early release 2007 CFS data. This model validated poorly to truck counts and OD patterns gleaned from truck intercept surveys at ODOT weigh stations that Kyle Hauger and I did in 1997-98 (to spin up first generation statewide model in TRANUS). We convinced ourselves at the time that further calibration of AA would likely improve the results, and we looked at various ways of allocating flows to external markets to specific external stations. 

The availability of the [Freight Analysis Framework](https://faf.ornl.gov/fafweb/) (FAF) was a game-changer, although Versions 1 and 2 did not compare well with the truck intercept surveys, either. The quality of the data appeared to improve dramatically starting in V3.2, and the current V4.5 appears to provide robust commodity OD tonnage and value data by primary mode of transport and commodity. At that point (V3.2) we updated CT to fuse the FAF data with PC matrices from AA, but the inconsistencies between them were so great that we suspended those efforts, again assuming that further calibration of AA would resolve the inconsistencies. After experimenting with several different approaches we found that using the AA make and use coefficients to allocate the FAF flows directly to alpha zones validated the best.

In TLUMIP5 we again tried lining up the PC flows from AA with the FAF and found that large discrepancies remained, that using PC flows morphed to truckload equivalents validated poorly, and that FAF flows allocated to alpha zones using AA make and use coefficients continued to work best. Thus, it would be fair to say that the two models remain only loosely integrated, and reveal inconsistent patterns as a result. However, directly comparing the two models is difficult in subtle ways. Validating CT to truck intercept surveys and counts makes sense, but it only validates that CT is generating the correct number of trucks by type (light, medium, heavy) and in plausible OD patterns. There is a lot of entropy in the latter, and of course the counts reveal nothing about what is inside of the trucks. It is conceivable that the AA commodity flow patterns are more robust than the FAF flows, which have never been validated at regional or national levels. 

A long-term solution that would improve both models would be to use the FAF and [CFS 2012 microdata](https://www.census.gov/programs-surveys/cfs/data/datasets.html) as constraints (or maybe targets) in NED and AA. That's not a simple upgrade, for there are bound to be inconsistencies between NED aggregate production, consumption, and trade levels and those depicted in FAF. But short of such reconciliation, coupled with the subjective nature and assessment of calibration in AA, it's doubtful that we can get these three models to tell exactly the same story. Whether we should make one last comparison of "latest and greatest" PC flows from AA to FAF 4.5 data is an open question, but I'm guessing they're not much closer than before.

I'm hoping that background puts what I will say about reconciling CT, FAF, and AA flows into context. My sense is that when doing __economic studies__ I agree with @jeabraham that I'd use AA data for analyses, as that ensures consistency across several models that use AA signals. Moreover, the evolution of the simulation through time ("feed-forward") is largely driven by AA, which can impose constraints and embody assumptions for a given scenario that the static FAF is wholly insensitive to. In earlier comparisons I did of high and low FAF forecast series we saw that they embody linear growth rates over time that don't match up well with NED's assumed rate of growth for Oregon.

If you're looking at __inter-regional trade__ or __flows between Oregon and other megaregions__ I would definitely use the FAF instead of AA data. AA represents external markets in a far more aggregate manner, and it seems a lot of shadow pricing adjustments are done in the external markets. Thus, the FAF probably depicts flows to and from Oregon better by virtue of its incorporation of OD data from several freight data sources, none of which were used in AA development or application.

Finally, it's an open question whether to use AA or CT data for __project or corridor analyses__. CT and FAF are completely consistent in both base and forecast years with respect to flows between FAF regions, so it is safe to consider them interchangeable at this level. Because CT based on FAF validates so much better than CT based on AA flows I would tend to use the former for this level of analyses. Moreover, I might scale the CT truck value and tonnage to match the AA totals for the same OD pairs to represent a range of value rather than a single number.

**Comment by jfdman** [comment]
A few comments:
1) AA is an aggregate model, no microsimulation.
2) The spatial scale of data should be mentioned somewhere. FAF data is only available by FAF zones which are very aggregate (one zone for Portland\Vancouver\Salem and another for the rest of Oregon), with similar aggregations outside of Oregon. So FAF might be useful for understanding the quantity of travel but not useful for OD Patterns outside of the 2 represented zones.
3) Should mention that which data source to use is also influenced by whether the scenario being modeled is a 'business-as-usual' type of scenario versus a 'major disruption' type of scenario. Can probably assume that one of the FAF forecasts will be applicable in BAU scenario, while MD scenarios would require a strong linkage to NED (dynamic with feedback) and AA.

**Comment by bettinardi** [comment]
I like all the context in Rick's post and agree with Joel's comments.  There's still a piece missing and I'm not sure the best way to complete this.

Rick's advice makes sense, but I'm still left with several questions on the specifics of how to take the recommendations, and mechanically program (or analyze) the proper SWIM data in the way that the comments suggest.   Meaning, it's not fully clear to me how to take the advise and use CT or AA output.  To fully clarify for myself, I think what we would have to do is take some past requests for information, and then work them through.  Document, this is the type of information being requested, and this is the table we used to pull the correct information, and this is the processing that was done to properly process that information.  So it seems like it would be a task for Rick and John to help and review the specific questions we are getting and the specific data we pulled and the specific processes we applied and provide direction and feedback on how they would advise each of those steps be completed...

**Comment by bettinardi** [comment]
I'm going to capture this in an email as well, but here's one piece/question I'm hoping we can answer to help close this issue:

Can we write a few paragraphs on CT wiki page to explain what it means to have a trip record from CT or FAF as tagged in the "dataset" field in the CT trip output table:  https://github.com/tlumip/tlumip/wiki/CT#outputs

I'm hoping that if we explain where the trips tagged as "CT" come from and the trips tagged as "FAF" come from it will help staff use this output correctly.  As part of that description, I'm hoping there can be a few sentences on why CT records can't be populated with a commodity, ton, and value.  Similarly why can't FAF records be populated with a time and distance.

If we can get a few paragraphs explaining these details to the user, I think it will resolve this standing issue.

| origin | tripStartTime | destination | tourMode | tripMode | truckID | truckType | sctg2 | value | tons | travelTime | distance | dataset |
|--------|---------------|-------------|----------|----------|---------|-----------|-------|-------|------|------------|----------|---------|
| 1      | 803           | 1344        | internal | loaded   | 1133    | CS        | NA    | NA    | NA   | 61.33731   | 47.78699 | ct      |
| 1      | 1156          | 1347        | Internal | loaded   | 1134    | CS        | 26    | 8851  | 23.5 | NA         | NA       | faf     |

**Comment by bettinardi** [comment]
One additional request from Ben after reviewing the thread and thinking about how to use CT to help with Metro's Freight model work:

"I might ask him [Rick] to also add a section at the end of the CT page that is a bulleted list of the most appropriate outputs for various purposes:

-	economic studies -  AA (and one line why)
-	inter-regional trade– FAF (and one line why)
-	flows between Oregon and other megaregions – FAF (and one line why)
-	project or corridor analyses – CT (and one line why)
-	etc…
"

**Comment by rickdonnelly** [comment]
There are a couple of issues traveling together in this thread that perhaps have different resolutions:
 
+ I will update the output documentation to make this clearer, but the `dataset` field in the CT output marks which part of the model gave rise to a particular truck tour. All of the truck flows with one or both trip ends outside of Oregon, as well as most long-distance trips (>50 miles) within Oregon, come from the FAF. By definition all FAF flows are trips, as tours are not reported in the CFS microdata or FAF (indeed, both report commodity flows [shipments], not tours). Trips that are marked 'CT' are segments of local truck tours that are generated separately from the FAF. The total tour distance is often more than 50 miles, but most of the individual legs -- trips -- are less than that. Finally, trips that are marked 'AA' are those that are synthesized based upon production, exchange, and consumption zones, as well as commodities, from AA flow matrices. The current implementation generates FAF trips instead of AA trips, so you won't find any of the latter in current model runs. But the hooks are still there. 
+ In hindsight I should use a different label than 'CT' in the `dataset` field of the CT output, as that is the model name rather than useful label for what part of CT generated the flows. Left to my own devices I'd rename it to LTT for "local truck tour," but am open to alternatives.
+ We can sample commodity, in terms of both value and tonnage, for CT/LTT trips from the AA flow matrices, as was originally specified. The gist was that we'd (1) convert the AA flows from annual dollars into tons, (2) sample commodity (or commodities) carried at the tour level -- which include services as well as freight -- based on total AA tonnage _production_ by commodity by beta zone, and (c) tag all trips in that tour as either carrying that commodity or empty (on return leg). You may recall that we discussed this during one of the peer review meetings, although I'll need to go back through my notes to pinpoint which one. My point then -- which I think is still valid today -- is that it is mechanically straightforward to do this, albeit at cost of increasing CT runtime because of all of the AA matrices that would need to be handled. But I was opposed to appending that info until we felt really comfortable with AA calibration and validation. I didn't want anyone using data from an uncalibrated model as robust info, so we agreed it was better to mark the commodity as missing values to prevent mis-interpretation and to remind ourselves that we still had this open loop to close once we had high confidence in AA. If you feel we're there then I'm fine adding the code back in to do this allocation.
+ It seems like a [vignette](http://r-pkgs.had.co.nz/vignettes.html) walking users through how the CT output might be used in economic studies, looking at inter-regional trade, project appraisals, etc. might be more effective than a paragraph about each of them. That way the user would see example code, data, and output as well as explanations. I can add just a paragraph about each use case to the wiki instead, as @bettinardi has suggested, but I'm not sure that it will go deep enough to satisfy the questions posed above. However, I'm willing to do that first, or in addition to vignette(s). The advantage of the paragraphs are that they're one hour worth of work, whereas we'll have to allocate budget to creating vignettes. Left to my own devices I'd just do the vignettes, but get that wiki is the TLUMIP standard for documentation.

**Comment by bettinardi** [comment]
Summary for WOC 7 -
This issue is tied to #88 and #129.  The idea is that RSG would be brought on to complete these three issues with Rick's support.  For this specific issue, #78, RSG would be asked to review all of the content captured on this issue thread and to boil it down to some guidance (in working with Rick and HBA) that can be added to the wiki.

**Comment by bettinardi** [comment]
From CT meeting on 9-8-22 -
It might work best to come back and revisit and close this issue after SWIM 2.6 is complete.  As SWIM 2.6 is finalized, and comparison of the latest FAF work and the latest AA work (both in 2.6) can be made.  And then the wiki guidance can be finalized using the discussion above and the latest comparison of the two value sources in SWIM.

**Comment by bettinardi** [comment]
I think the wiki now clearly states what's in the output file well enough so that we can use the information coming out of all pieces of SWIM correctly.
