### ISSUE TITLE
Implement NED Feedback

### ISSUE THREAD

**Issue by jfdman** [tlumip/tlumip#86]
Implement NED feedback in SWIM 2.6

**Comment by bettinardi** [comment]
Summary for WOC 7 - 
Currently ODOT has a functional SWIM 2.6 with updated PopSim and AA.  ODOT is running a reference and Rough Roads Ahead (RRA) scenario to test an extreme scenario against a reference that might benefit from turning feedback on.  ODOT will finish the runs and then do a test with the RRA scenario where feedback is turned on.  The intent of the test (playing with the feedback settings) will be to see if similar impacts to those reported in past RRA analysis can be achieved.  Assuming something somewhat similar can be achieve, the test and findings will be written up (by ODOT) and then shared with Josh (OEA) and possibly others.  A review team will be assembled.  The purpose of the review team will be to understand the purpose, setup, and testing of the feedback feature, and then to help guide what "correct" settings / use of the feedback feature should be for future analysis.  The review team will likely not want to provide an "answer" to how to setup the feedback, but the discussion will probably allow ODOT and RSG to document some reasonable guidelines to use of the feedback feature for future analysis - at least that's the hope and intent of this issue/task.

**Comment by jeabraham** [comment]
Sounds good. The AA economic performance measures should be in a good state to use to drive NED feedback.

We'll have to watch/investigate what technology scaling does.  When NED feedback chooses to grow an industry more slowly, technology scaling might reduce the consumption rates of that industry's output. Say things suck for healthcare, so healthcare shrinks (or grows more slowly) due to NED feedback.  Households then obviously have to consume less healthcare and/or go to California or Mexico for their health care .  To the extent that they just consume less healthcare, there is no incentive for the industry to rebound. To the extent that they're going out-of-state for their health care, there is still opportunity for the local industry to grow to re-capture the local demand.  Technology scaling adjusts both local consumption and imports/exports to keep things balanced. 


We could tweak the way the final "f" is calculated/applied if there are problems. The plan we had was to put an exponent on the (1+f) term and/or the (1-f)*U term and/or the (1-f)*E term.  If we allow different exponents for different terms, f would have to be found numerically (rather than algebraically) but that shouldn't be a problem. 

--
John Abraham
jea@hbaspecto.com
403-232-1060

**Comment by bettinardi** [comment]
Sounds like we will need to bring HBA in as we review the feedback results.  I'm just getting ready to kick-off a feedback run.  This is a note to the issue that **we need to go back and update the wiki**.  https://github.com/tlumip/tlumip/wiki/NED#using-ned-feedback

The wiki does not properly reference the properties - how to turn on feedback (true/false flag) and how to modify the elasticities in the code:

https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L170

https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/NED.py#L115

**Comment by bettinardi** [comment]
@jfdman - I thought I was going to be able to figure out how to run feedback, but I'm not able to figure out from the instructions and the code how to set this up properly (specifically how to point the code back to a reference scenario to calculate the feedback).  Thoughts on how I can get support to update the instructions to figure out how to set this up?

Atting Ben too - @bstabler

**Comment by bettinardi** [comment]
The run I setup just completed and I think we have learned two things:
  1.  I don't know how to turn on NED Feedback.  So the first step of this issue will be to go back and improve the instructions/wiki so that it is clear how the user turns on and adjusts the Feedback.
  2.  AA seems to clearly be having a hard time with the extreme RRA scenario (taking a very long time to converge and wildly oscillating from year to year).   Feedback may help, but it seems highly likely that there will need to be an HBA component of this issue/task to revisit the AA setup and determine the best way to setup AA for scenarios with extreme changes and/or with feedback applied.

**Comment by bstabler** [comment]
- @bettinardi share latest NED code since the repo has an old version
  - run it
  - get it merged in, i.e. maybe create new global properties and update the ned.py script as needed
  - update the documentation for how to run it
  - superficial results check, which likely results in a new issue to make revisions / calibration to the model

**Comment by bstabler** [comment]
the latest NED code is at https://github.com/tlumip/tlumip/blob/latest-ned/root/scenario/model/code/NED.py

**Comment by nsdhakar** [comment]
The setup is working with the new script, though the following should be resolved before closing the issue:
1. inputs\t0\trade_forecast.csv wasn't available in the setup. Presently, using an older file. Need to find out how that file is created.
2. In global properties template, "ned.feedback_elasticity" is currently set to 1.2. Need to do tests to come up with a reasonable elasticity value for NED feedback.
3. In global properties template, "ned.reference_prior_activity_summary.path" needs to be updated to a correct reference scenario path.

**Comment by bstabler** [comment]
@RAKnudson Notes from discussion with Carl Batten about NED feedback, August 31, 2020

Developing the value for the NED feedback elasticity is an iterative process based on the composite utilities. 

Step 1: run SWIM reference scenario though time; evaluate the composite utilities for relationship patterns. The composite utilities indicate the “desirability” of the area, which is implemented using the feedback elasticity. 

Step 2: Refine the elasticity term until it produces the best fit with historical data by scaling the elasticity based on the composite utilities. Start with the value of 1.0 and refine from there. 

Step 3: Once an elasticity term consistent with historical data has been developed, run SWIM out into the future with feedback turned on and evaluate forecast results for reasonability.

**Comment by bettinardi** [comment]
No one believed this day would come, but I am finally closing this issue with a successful resolution :)
