### ISSUE TITLE
Check world zone distances

### ISSUE THREAD

**Issue by jfdman** [tlumip/tlumip#87]
From Alex: I'm very concerned that the function on lines 818 - 845 of:
https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/SWIM_VISUM_Main.py
is not interfacing (using) the WorldZone Distances correctly:
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/t0/WorldZoneExternalStationDistances.csv
I have looked over some previous Beta zone matrices and they don't seem to make much sense or correspond to the distances in the csv file above. We need to revisit this function and verify it is working correctly and update it if it is not.

**Comment by jfdman** [comment]
Ben: Is it possible the problem is in the cast? In python 2, dividing int by float returns float. why cast to an int first?

**Comment by jfdman** [comment]
Alex to provide the matrix.

**Comment by jfdman** [comment]
Probably not a problem with casting.

**Comment by bettinardi** [comment]
In my attempts to re-familiarize myself with this issue, I have not yet found the fire, but I have found some smoke that leads to a series of questions:

 - There are two files that seem to specify the same information, which is correct and which is not used.  Can we delete the one that's not used -
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/parameters/worldZoneDistances.csv
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/t0/WorldZoneExternalStationDistances.csv

 - related to the confusion around two different files, the files are each specified slightly differently, and they each have a different count of how many times the world markets are repeated for external stations.   Which is correct, and what is the proper way to code this input given the function.

- I can't make sense of the external-external (world market to world market) values.  Do we know if they are hard specified by an e-e matrix (doesn't seem to be since they change over time), or if they are calculated through by the function identified above.  No matter how they are calculated, I'm thinking this model shouldn't care about world-market to world market flows, since the model only deals with economic flows to the SWIM area (not to and from every country in the world, like IL to FL economic flows).  Assuming I'm right and this part of the matrix doesn't matter, can we update to make those values something like 9999, or 0, so that it's more clear that the e-e part of the beta matrix doesn't matter.

I'm still trying to track down the original email that I must have sent to Joel around Nov 7th 2017 - if that can be found, please provide incase it provides any additional context into this issue.

For context, here are the world market zone definitions for anyone digging into the input files and code: 

| Zone number | code  | Distance beyond Halo | external stations | definition                                |
|-------------|-------|----------------------|-------------------|-------------------------------------------|
| 6001        | N     | 453/510              | 5002              | Washington and Canada                     |
| 6002        | NE    | 453/510              | 5003, 5004        | Northern states of the Midwest            |
| 6003        | E     | 1,661/1,399          | 5007              | Central and Eastern USA                   |
| 6004        | S     | 1,977/1,799          | 5010              | California, Southwestern states,   Mexico |
| 6005        | Ocean | 1500/600             | 5012              | Rest of the world                         |
| 6006        | Local | 75/75                | Non-Interstate    | Local markets in neighboring   states     |

**Comment by jeabraham** [comment]
AA doesn't represent any External-External flows, the world markets are only used in AA for Internal-External and External-Internal.

--
John Abraham
jea@hbaspecto.com
403-232-1060

**Comment by bstabler** [comment]
I can see in the properties file that there are two tokens, one for each file:

```
ta.world.zone.distances = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.INPUTS@/parameters/worldZoneDistances.csv

world.to.external.distances = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.INPUTS@/t0/WorldZoneExternalStationDistances.csv
```

In ```SWIM_VISUM_Main.py``` I can see that ```ta.world.zone.distances``` is used for getting the distance between external stations and world markets for calculating skims.  See this [line](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/SWIM_VISUM_Main.py#L849).  Probably the funny E-E values come from the matrix correction function, which I'm not familiar with.  It looks like it is taking the average distance between zones and calculating a travel time based on an assumed speed.  The assumed speed is commented above as:

```
#speed in miles per minute to compute skims between world markets and external stations
speed = 50.0/60.0    #Visum outputs skim in minutes and distance in miles
```

So, I think we could update the ```matrixCorrection``` function to write a default value for EEs.  I think we should also rename the function to something more meaningful.  

I'm guessing ```world.to.external.distances``` is used by AA?  If I remember correctly, the AA source code is in HBA's SVN server since we're only storing the [AA jar](https://github.com/tlumip/tlumip/wiki/build) in the repo.

**Comment by bettinardi** [comment]
The two files are different but not by much.  There values are the same it's just that t0 has more world market to external station relationships - it's more complete.  So we should see if we can make python use the file that AA is already using - and just have one.

**Comment by bettinardi** [comment]
WOC 7 summary of the issue - 

There are two inputs that are basically the same in SWIM:
ta.world.zone.distances = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.INPUTS@/parameters/worldZoneDistances.csv

world.to.external.distances = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.INPUTS@/t0/WorldZoneExternalStationDistances.csv

The second one is the file that was deemed more complete / correct in the review above, but the first one is the one that is used by the code currently.  The first property - ta.world.zone.distances - should be deleted, and the file should be removed.  The code should be changed to point to the second property.   The code then needs to be reviewed to ensure that it is developing the e-e distances/times correctly, and any changes to the input or coding needed should be made.

**Comment by bettinardi** [comment]
@nsdhakar - I am reviewing this to close it.  A couple of questions.  I see that parameters/worldZoneDistances.csv still exists (it hasn't been deleted), is there any reason that it was not deleted that I should be aware of?

Also, I have reviewed the properties, files, and run the code - all of that seems correct (except the file deletion).  The last thing I want to check is that the code was reviewed and that the code was edited to use world.to.external.distances in place of ta.world.zone.distances.  Can you help point me to the change in the code.  And (related) can you provide a sentence or two on any checks that were done to make sure that the slightly different format of WorldZoneExternalStationDistances.csv would work for ta.world.zone.distances.

Thank you

**Comment by nsdhakar** [comment]
@bettinardi : Yes, the file should be deleted. Looks like, while pushing changes, I focused more on code changes and not on removing the file. I will remove it. You can see the code changes by looking at my commit, it will show you the diff between the old and new files. Let me know if you need any help there.

I made the following changes:

- In the global template properties, pointed the token self.worldZoneDistances to "world.to.external.distances"
- In SWIM_VISUM_Main.py (steps are provided as comments in the code), the following steps are performed to bring the data in the same format as before when used 'ta.world.zone.distances'
   - reading the new file and sort by ExternalStation and WorldMarket
    - find indices of duplicate ExternalStation
     - remove duplicate ExternalStation based on their indices

**Comment by bettinardi** [comment]
In the test I just did, PT hung when I deleted parameters/worldZoneDistances.csv.
I'm guessing PT most load this file - @nsdhakar can you please check.

I'm starting another run where I add that file back in to verify that's what is causing the PT hangup.

**Comment by bettinardi** [comment]
As a follow-up, when I added parameters/worldZoneDistances.csv back, PT ran fine.  So I think PT must be using this file.

**Comment by bettinardi** [comment]
Hi @nsdhakar, I'm doing a final review to close this.  I'm seeing that in Dec, I attempted to run this and PT was crashing.  In the latest run it is not crashing - can you provide some quick context as to whether there was an issue in PT that you had to address - was PT using this file...

Also, in your tracking sheet, there is a question mark next to wiki update.  While this is still somewhat fresh it would be great to capture a paragraph on this file in whichever module is impacted.  Is PT the impacted module?  If so, a quick paragraph on this input and how to establish it would be great to complete before this issue is closed.

**Comment by bettinardi** [comment]
As best as I can tell my latest SWIM runs are operating without the "parameters/worldZoneDistances.csv" file, so I think that part is resolved.  

@nsdhakar - the last thing I was going to do was read the wiki real fast and then close the issue - but I'm not finding the new text on the wiki - can you point me to the new text on this input file.

**Comment by nsdhakar** [comment]
@bettinardi : here it is: https://github.com/tlumip/tlumip/wiki/Traffic-Assignment#inputs. Look at the third input file.

**Comment by bettinardi** [comment]
Can the wiki be clarified just a little further.  It sounds like it does a pruning process twice - once for the external stations (5000 series) and once for the world market series (6000 series).  If so, this helps explain why some external stations and world markets are repeated more than once, even though only the first is used.  If this processing is happening twice at the two different levels.  Can another sentence or two be added to try and clairfy.  I'm thinking maybe a last sentence could be added that says something like, "This processing is conducted twice, once as the external station (alpha zone) level and once at the world market (beta zone) level".

**Comment by bettinardi** [comment]
@nsdhakar - My suggested text for the wiki in the comment above is the last piece to closing this issue.  I don't know the change well enough to confirm my suggested edit to the wiki.  Can you please review and finalize the wiki accordingly and then close the issue.  Thank you

**Comment by bettinardi** [comment]
@nsdhakar - a quick flag that I'm hoping for the small edit in the wiki from two comments above.  If you can confirm and complete that wiki change, then I can close this issue.

**Comment by nsdhakar** [comment]
@bettinardi - The retained input file (WorldZoneExternalStationDistances.csv) has all pairs between external stations and world market. That means one external station may have records for multiple world markets. However, the eliminated input file ("parameters/worldZoneDistances.csv") contains only **_one_** world market for every external station. To keep only one world market in the way it was in the eliminated file, the file is first sorted **_only_** once by (external station and world market) and then kept only the first record of an external station when duplicate world market correspondence. I think this process is captured in the wiki already.

To your suggestion of adding a text saying "This processing is conducted twice, once as the external station (alpha zone) level and once at the world market (beta zone) level". This isn't true, the processing is done only once. It's just that sorting is done using two fields (ExternalStation and WorldMarket) - this is to identify what records to keep. Next, only the first record is kept if duplicate records for ExternalStation.

I have added a few clarifying text such as "sorted ascendingly by two fields" and "keep only the first record for the duplicate ExternalStation records." Please let me know if it is still not clear. 

> WorldZoneExternalStationDistances.csv – Provides distance between external stations and world markets. To/from distances for all possible external station and world market pairs are included. The file structure is: WorldMarket, ExternalStation, DistanceFromWorldMarket, DistanceToWorldMarket. In the traffic assignment module, this complete file is processed to keep only one world market for each external station and then used in updating beta zone level skims (distance and time = distance/speed) for external stations. The file processing includes the following sequential steps: read the file, sort ascendingly by two fields (ExternalStation and WorldMarket), find records of duplicate ExternalStation, and keep only the first record for the duplicate ExternalStation records.

**Comment by bettinardi** [comment]
I think I now understand, what was confusing me is that why do we have an input that doesn't align with the instructions.  So to confirm, the input is bad, it has rows that aren't used.  Is that correct?  If so, I will leave the wiki description but maybe add something to say "if the user adds extra records for external stations, it will only use the first records found."  I will then clean up the input file to remove the following in bold.  Will the code still work correctly if I remove the bold rows below?

| WorldMarket | ExternalStation | DistanceFromWorldMarket | DistanceToWorldMarket |
|-------------|-----------------|-------------------------|-----------------------|
| 6001        | 5002            | 453                     | 510                   |
| 6001        | 5003            | 453                     | 510                   |
| 6002        | 5004            | 1661                    | 1399                  |
| 6003        | 5007            | 1977                    | 1799                  |
| 6004        | 5010            | 914                     | 867                   |
| 6005        | 5012            | 400                     | 1000                  |
| 6006        | 5001            | 75                      | 75                    |
|**6006**        | **5002**            | 75                      | 75                    |
| **6006**       |**5003**            | 75                      | 75                    |
| **6006**        | **5004**            | 75                      | 75                    |
| 6006        | 5005            | 75                      | 75                    |
| 6006        | 5006            | 75                      | 75                    |
| **6006**        | **5007**            | 75                      | 75                    |
| 6006        | 5008            | 75                      | 75                    |
| 6006        | 5009            | 75                      | 75                    |
| **6006**        | **5010**            | 75                      | 75                    |
| 6006        | 5011            | 75                      | 75                    |

**Comment by nsdhakar** [comment]
Before cleaning up the retained file the way you suggested, we need to make sure that this file is not being used elsewhere. As part of this task, we simply eliminated one input file by generating that file from this retained file. But we do not know if the retained file is used elsewhere that requires this format. We can do that check in WOC9. Is that okay?

**Comment by bettinardi** [comment]
I have started a run with them removed, we will see how that run performs.  So, if we feel it needs more review after that test we can add to WOC 9 - I will follow-up in a few days after the run completes.

**Comment by nsdhakar** [comment]
@bettinardi - wondering how your test run go?

**Comment by bettinardi** [comment]
I'm seeing a pretty sizeable impact to external station volumes - so I'm thinking that file might have had an impact, but I made two changes, one was the change to - WorldZoneExternalStationDistances.csv, and one was the code correction that @goreaditya made to for issue 127.  https://github.com/tlumip/tlumip/issues/127.  So I'm running one more time to try and verify where the impact to external station volumes is coming from.  But I'm guessing that it's the world zone external station distances file, which makes me think it must be impacting another part of the code, so after I confirm, we likely do need a task in WOC 9, that helps us complete the wiki for - WorldZoneExternalStationDistances.csv

**Comment by nsdhakar** [comment]
Yes, given the bigger set in this file and this file potentially being used elsewhere, we decided to use this file and eliminate the other one with a subset. In WOC9, we can look into the code to see how this file is being used in the model and if multiple world markets to one external station are necessary.

**Comment by bettinardi** [comment]
As best as I can tell there is no impact from removing the extra rows in the WorldZoneExternalStationDistances.csv file.  I did tests and saw some 5% VMT swings in smaller (arterial) external stations, and was concerned.  But as best as I can tell, those smaller external stations can just swing 5% between scenarios for any given year (based on identical scenarios I ran side-by-side).  So at this point I'm closing the issue and calling it complete.
