### ISSUE TITLE
Negative Results in the Select Link Demand Matrices

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#91]
When we run/assign the SL demand matrices we get a warning of negative values in the demand matrices.  That's the primary issue copied from issue #59, here's the comment :
Initial testing returns a warning identifying negative values in the demand matrices. We will need to track down if there are indeed negative values in the matrices and where they are coming from.

Secondary issues that are related (and would help in running this issue) are that we would like to setup the SL link demand matrices to run automatically at the end of the select link run.  Below are the notes on aspects to address in getting the SL demand matrices assigned after a completed SL run:

 - demand segements need to be updated to include the 16 new classes (4 periods x two modes x sl and remainder)
 - The matrix listing descriptions need to be updated so that the name is the same as the dsegcode.  If this step is completed than the new demand segements will automatically point to the 16 new matrices.
 - then an xml procedure file needs to be run (I have already set that up).  I think we need to consider whether we want to setup some additional formula matrices and have all of the demand stuff and matrices placeholders setup in the input version file.  That might simplify.  The reason I suggest formual matrices, is because I don't know if we will care about SL analysis by period as much as looking at a daily assignment, and so I think we will want the default to do a 4 way demand segement assignment instead of a 16 way assignment, where we collapse on the period and just have a daily by mode and select link versus remainder.
 - We will also need a graphic parameter file that auto loads after assignment is complete, so that the user can just open the select link version file and see what the select link looks like without any additional work.

**Comment by nsdhakar** [comment]
**Regarding the primary issue (negative values in demand matrices):** 

The negative values exist in remaining SL demand matrices and are due to some OD pairs in a SL matrix containing more demand than total demand for the pairs. This happens for the pairs that have their trip paths traversing through multiple select links. 

To calculate a SL demand matrix, a flow bundle is run for each select link separately and all flow bundles are then combined together to create SL demand for the sub-area (all select links).  By running flow bundle separately for each link, one OD trip is counted as 2 if its path is traversing through 2 select links This results in more SL demand for the OD pair then the corresponding total demand. Then when remaining demand is calculated by subtracting the SL demand from the total demand the value for the OD pair is calculated as negative.

**Solution:** Count number of select links encountered in each OD path and then divide SL demand by the count to get actual SL demand.

**Comment by bettinardi** [comment]
That solution seems good to me.

**Comment by bettinardi** [comment]
Actually, as I think about this a little more.  I'm pretty sure that we mainly get this issue for remaining matrices generated with just one select link chosen.  

Could you please make sure to review and test a scenario where just one select link is used.
